### ISSUE TITLE
Error handling in dropdowns

### ISSUE THREAD

**Issue by AOikonomidis** [oblique-bit/oblique#15]
Hello,

I have a reactive form with some input fields and a dropdown. I use the obErrorMessages directive for the error handling in the inputs but I would also like to add the same error handling for the dropdown. I used the obErrorMessages directive but this doesn't seem to work with the dropdown(I am using mat-select). The dropdown field is getting red as it should but no error messages are shown. Is there a way to show the error messages in the dropdown similar to the inputs with obErrorMessages?

Thanks in advance

**Comment by gillerr** [comment]
Hello

As of Oblique 5, the `obErrorMessages` directive only works with `matInput` . This have been fixed in Oblique 6 which also works with `mat-select`. Support for checkboxes and radio buttons is still missing.

If you cannot wait for Oblique 6, you have to display the error message manually:
`<mat-error *ngIf="form.get('field').errors.required">Some error message</mat-error>`

**Comment by AOikonomidis** [comment]
Thank you for the immediate response. When is the release for Oblique 6 scheduled?

**Comment by gillerr** [comment]
Oblique 6 is scheduled in January 2021. Probably next week as we are almost ready with it.

**Comment by AOikonomidis** [comment]
Thank you!

Have a nice day!
