### ISSUE TITLE
Framework-agnostic version of Oblique 🠒Web Components

### ISSUE THREAD

**Issue by hupf** [oblique-bit/oblique#39]
As far as I understand, the _oblique_ framework is strictly tied to Angular. Even the Material or Bootstrap "themes". It would be nice if Oblique could be used with any framework or no framework at all – we, for example, use React in our project.

A possible approach would be to provide a Web Components version of the framework for ideal compatibility with all frameworks/libraries/tools that work with HTML.

**Comment by gillerr** [comment]
Oblique is build on top of Angular and will likely remains so in the future. The reason is that almost all of our clients do use Angular.

With Angular Elements, it would be possible to distribute Oblique as Web Components but this would be no straightforward task and we're unsure of how well it could be integrated with other technologies. According to you, how many applications would use a Web Component Oblique?

That being said, Oblique's CSS is build to be usable without Angular. This means you could let React build the relevant HTML and then simply link Oblique's CSS into your application. The layout composer (https://oblique.bit.admin.ch/layout-composer) on ObliqueDocs demonstrates exactly that. This is obviously limited, but still better than starting everything from scratch.

The other alternative would be to wait for the new version of the Styleguide that should be more application friendly (the actual one really is for Websites).

Cheers
