### ISSUE TITLE
Improvement translation testing

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#52]
I tried to test if my code handles correctly the language change and I think that the `onLangChange` is never executed in the mock. I believe that when we use the `use()` function it should also emit on the `onLangChange` emitter. (I might be wrong since I'm new in testing) https://github.com/oblique-bit/oblique/blob/adc24a67f5fe9b70e5c49c9ac330ecd41d510b8f/projects/oblique/src/lib/_mocks/mock-translate.service.ts#L39

**Comment by gillerr** [comment]
Hi

Effectively, the `ObMockTranslateService` is just a mock, meaning it does nothing. It's only there to simplify the tests and improve their performances. We think that a unit test should only test one unit (e.g. a component, a service or a directive) and to have it really limited to the system under test, we mock everything else so that side effects are excluded.

As of now, you'll have to implement your own mock for the `TranslateService` or import the `TranslateModule` in your `TestBed` in order to test the language change.

That being said, your remark is relevant and I'll have a look a the mock to see if it can be improved.

Cheers

**Comment by ice-blaze** [comment]
Indeed it would be better that I use the word `fake` instead of `mock` (I guess). I agree that unit tests should focus only on the current file. But in this case I don't test that the mock works but I test that my component reacts correctly to the changeLanguage event. So indeed I fired manually the onLanguage change event ` translateService.onLangChange.emit({ lang: 'en', translations: undefined });`.

Mocks should still be used carefully because if you mock everything then when there is a refactoring the mock is most of the time not updated and then your test doesn't fail. (At google they avoid mocks because of this reason. They went from: no tests -> full mocks -> mock only when it's not possible to use real implementation.) https://testing.googleblog.com/2013/05/testing-on-toilet-dont-overuse-mocks.html

Doing a fake class means that you have to fake all functionalities and not juste the onLanguageChange(). So I can also understand that it might require too much time for the usefulness of the output ^^' (I leave it to you if you want to close or keep this issue open)

**Comment by ice-blaze** [comment]
The new removal of ObliqueTestingModule is a consequence of this issue?

**Comment by c-saner** [comment]
Hello,

The ObliqueTestingModule has been deprecated with Oblique 9 and will be removed with Oblique 10.

This module task was to simplify the TestBed configuration, however this approach did lead to numerous problems. Such as inability to test projected content or to trigger something within Oblique. And conceptually, each project should be responsible for how dependencies should be mocked. This is why this feature will be removed without replacement.

Projects that rely on ObliqueTestingModule should start importing relevant Oblique modules as well as the TranslateModule in their test cases.

As the ObliqueTestingModule  will be removed, can we close this issue?

**Comment by ice-blaze** [comment]
Yes we can close it
