### ISSUE TITLE
Oblique-Doku zeigt noch nicht Version 10

### ISSUE THREAD

**Issue by jonashofer** [oblique-bit/oblique#93]
Nur ein kleiner Hinweis, v10 ist ja noch sehr frisch aber ich wollte gerade mein Projekt upgraden und da hat es mich verwirrt, dass auf der [Doku-Seite](https://oblique.bit.admin.ch/home.html) noch keine Rede davon ist, und ich dachte ich muss auf Angular v14 upgraden, dabei gibt es ja neu Oblique v10 was mit Angular v15 kompatibel ist - aber das npm-Paket ist noch nicht published? -> Ich erhalte peer-dependency Issues beim Upgraden - was ist die aktuellste Kombination? ```npm outdated``` gibt nach dem Upgrade folgenden (lustigen) Output:
![image](https://user-images.githubusercontent.com/12249259/220474857-725df5c5-69f0-4bf3-bcb8-7de827dfd1eb.png)

**Comment by ice-blaze** [comment]
It's just a personal comment (from the open source community). But it would be better to write in english. Two main reasons:
* There are more people who understand english (documentation is always in english)
* Searching old issues is always helpfuf. If old issues use different languages you might have missed the one that was written  with doku instead of documentation.

But thank you for your feedback :) I'm happy to see more people involved into oblique 👍

**Comment by gillerr** [comment]
Hi @jonashofer 

Thanks for your input and sorry for the late answer.

Due to a bug on our deployment pipeline, Oblique 10 have been published under the `next` tag, this is why `npm outdated` was listing `9.3.2` as the latest version.

To avoid confusion, we didn't want to deploy ObliqueDocs Version 10 as long as this bug wasn't fixed.

Oblique 10 has now been republished under the latest tag, ObliqueDocs Version 10 has been deployed. and the pipeline bug has been fixed.
