### ISSUE TITLE
oblique-material.css Missing

### ISSUE THREAD

**Issue by laz4triumph** [oblique-bit/oblique#99]
Hi,
I'am using  "@oblique/oblique": "^10.0.2" and after npm install cmd the file  _node_modules/@oblique/oblique/styles/css/oblique-material.css is missing.
What's wrong?
Many thanks.
Luca

Here my package.json

{
  "name": "web-admin.frontend",
  "version": "0.0.0",
  "scripts": {
    "start": "ng serve",
    "build": "ng build",
    "start-prod": "ng serve --configuration production --port 4204",
    "watch": "ng build --watch --configuration dev",
    "test": "ng test",
    "lint": "ng lint",
    "format": "npm run lint -- --fix"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.2.0",
    "@angular/cdk": "^15.0.0",
    "@angular/common": "^15.2.0",
    "@angular/compiler": "^15.2.0",
    "@angular/core": "^15.2.0",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^15.2.0",
    "@angular/localize": "^15.2.5",
    "@angular/material": "^15.2.5",
    "@angular/material-moment-adapter": "^15.2.5",
    "@angular/platform-browser": "^15.2.0",
    "@angular/platform-browser-dynamic": "^15.2.0",
    "@angular/router": "^15.2.0",
    "@ngx-translate/core": "^14.0.0",
    "@oblique/oblique": "^10.0.2",
    "@popperjs/core": "^2.0.0",
    "angular-oauth2-oidc": "^15.0.1",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "rxjs": "~7.8.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-builders/jest": "^14.0.0",
    "@angular-devkit/build-angular": "^15.2.5",
    "@angular-eslint/builder": "14.4.0",
    "@angular-eslint/eslint-plugin": "14.4.0",
    "@angular-eslint/eslint-plugin-template": "14.4.0",
    "@angular-eslint/schematics": "14.4.0",
    "@angular-eslint/template-parser": "14.4.0",
    "@angular/cli": "~15.2.5",
    "@angular/compiler-cli": "^15.2.0",
    "@types/jest": "^28.0.0",
    "@typescript-eslint/eslint-plugin": "5.43.0",
    "@typescript-eslint/parser": "5.43.0",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.0.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^28.0.0",
    "jest-sonar-reporter": "2.0.0",
    "prettier": "^2.0.0",
    "tslib": "^2.5.0",
    "typescript": "~4.9.4"
  },
  "title": "WebAdmin"
}

**Comment by gillerr** [comment]
Hi @laz4triumph 

With Oblique 10, Bootstrap has been completely removed, meaning that Material is the only remaining theme. As such `oblique-material.css` has been merged with `oblique-core.css` and don't exist anymore. You simply need to remove the file from `angular.json`

This change is actually handled by the Schematics, I encourage you to update Oblique with `ng update @oblique/oblique` instead of `npm i `. Actually, now that you have updated Oblique manually, you should still execute the Schematics to let Oblique automatically fix all its breaking changes: `ng update @oblique/oblique --migrate-only --from 9 --to 10`
